[package]
name = "actix-authentication-middleware"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
reqwest = { version = "0.12.15", features = ["json", "multipart"] }
anyhow = "1.0.98"
